Repository vapor/sql-kit, pull requests merged in 2020-02, with the labels that each got.

#91 Update SQLBinaryOperator.swift to include "like" and "notLike"
  Sources/SQLKit/Query/SQLBinaryOperator.swift
Labels: bug

#84 Add several useful helper methods to `SQLSelectBuilder` and `SQLRow`
  Sources/SQLKit/Builders/SQLAlterTableBuilder.swift
  Sources/SQLKit/Builders/SQLCreateTableBuilder.swift
  Sources/SQLKit/Builders/SQLInsertBuilder.swift
  Sources/SQLKit/Builders/SQLSelectBuilder.swift
  Sources/SQLKit/Query/SQLFunction.swift
  Sources/SQLKit/Query/SQLQueryString.swift
  Sources/SQLKit/SQLRow.swift
  Tests/SQLKitTests/SQLKitTests.swift
Labels: enhancement

#92 Add SQLDistinct and isDistinct
  Sources/SQLKit/Builders/SQLSelectBuilder.swift
  Sources/SQLKit/Query/SQLDistinct.swift
  Tests/SQLKitTests/SQLKitTests.swift
Labels: enhancement, semver-minor

#93 Implement remaining binary operators
  Sources/SQLKit/Query/SQLBinaryOperator.swift
  Tests/SQLKitTests/SQLKitTests.swift
Labels: bug, semver-patch

#86 Add support for creating and dropping triggers
  Sources/SQLKit/Builders/SQLCreateTriggerBuilder.swift
  Sources/SQLKit/Builders/SQLDropTriggerBuilder.swift
  Sources/SQLKit/Query/SQLCreateTrigger.swift
  Sources/SQLKit/Query/SQLDropTrigger.swift
  Sources/SQLKit/SQLDialect.swift
  Tests/SQLKitTests/SQLKitTests.swift
  Tests/SQLKitTests/SQLKitTriggerTests.swift
  Tests/SQLKitTests/Utilities.swift
Labels: enhancement, semver-minor

#87 Adds support for a drop table behavior clause
  Sources/SQLKit/Builders/SQLDropTableBuilder.swift
  Sources/SQLKit/Query/SQLDropBehaviour.swift
  Sources/SQLKit/Query/SQLDropTable.swift
  Sources/SQLKit/SQLDialect.swift
  Tests/SQLKitTests/SQLKitTests.swift
  Tests/SQLKitTests/Utilities.swift
Labels: enhancement, semver-minor

#88 Add optional autoincrement function expression to SQLDialect
  Sources/SQLKit/Query/SQLColumnConstraintAlgorithm.swift
  Sources/SQLKit/SQLDialect.swift
  Tests/SQLKitTests/SQLKitTests.swift
  Tests/SQLKitTests/Utilities.swift
Labels: enhancement, semver-minor

#94 Alter column data type support
  Sources/SQLKit/Builders/SQLAlterTableBuilder.swift
  Sources/SQLKit/Query/SQLAlterColumnDefinitionType.swift
  Sources/SQLKit/Query/SQLAlterTable.swift
  Sources/SQLKit/SQLDialect.swift
  Sources/SQLKit/SQLSerializer.swift
Labels: enhancement, semver-minor

#97 Fix multi-column update
  Sources/SQLKit/Query/SQLAlterTable.swift
  Sources/SQLKit/SQLDialect.swift
  Sources/SQLKitBenchmark/SQLBenchmark+Planets.swift
  Tests/SQLKitTests/SQLKitTests.swift
  Tests/SQLKitTests/Utilities.swift
Labels: bug, semver-minor

#98 Release Candidate 1
  .github/workflows/test.yml
  Package.swift
  README.md
Labels: enhancement
