Repository vapor/sql-kit, pull requests merged in 2021-02, with the labels that each got.

#122 Resurrect support for Codables with nullable fields
  .github/workflows/test.yml
  Sources/SQLKit/SQLQueryEncoder.swift
  Tests/SQLKitTests/SQLKitTests.swift
Labels: semver-patch

#123 Revert "Resurrect support for Codables with nullable fields (#122)"
  Sources/SQLKit/SQLQueryEncoder.swift
  Tests/SQLKitTests/SQLKitTests.swift
Labels: bug, semver-patch

#124 Allow Codables with nillable columns to encode as nil, if they wish
  .github/workflows/test.yml
  Sources/SQLKit/Builders/SQLInsertBuilder.swift
  Sources/SQLKit/SQLQueryEncoder.swift
  Tests/SQLKitTests/SQLKitTests.swift
Labels: enhancement, semver-minor
